# Generated by Django 5.0.6 on 2024-06-02 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_image',
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='products'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
